// <auto-generated />
namespace ReactApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatemodelfortestride : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatemodelfortestride));
        
        string IMigrationMetadata.Id
        {
            get { return "201807022048341_update model for test ride"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
