"use strict";

module.exports = {
    GET_BIKES: 'GET_BIKES',
    GET_BIKES_RESPONSE: 'GET_BIKES_RESPONSE',
    GET_ORDERS: 'GET_ORDERS',
    GET_ORDERS_RESPONSE: 'GET_ORDERS_RESPONSE',
    GET_TEST_RIDES: 'GET_TEST_RIDES',
    GET_TEST_RIDES_RESPONSE: 'GET_TEST_RIDES_RESPONSE',
    CREATE_ORDER: 'CREATE_ORDER',
    TEST_BIKE: 'TEST_BIKE',
    RECEIVE_CREATE_ORDER_RESPONSE: 'RECEIVE_CREATE_ORDER_RESPONSE',
    RECEIVE_TEST_BIKE_RESPONSE: 'RECEIVE_TEST_BIKE_RESPONSE'

};